// It's difficult to think of a proper database design at this point, so I am going to create a false database to test out my chat application and play around with its functionality.

const cssValues = {
  first: "container-fluid messages first",
  second: "container-fluid messages second",
  third: "container-fluid messages third", // Doesn't look that good.
};

let Users = [
  {
    rNum: "MS203538",
    name: "Blessy",
    fromSJU: false,
    college: "Mount Carmel College autonomous",
    grpName: "Awakeners",
    password: "6366222268",
    css: cssValues["first"],
  },
  {
    rNum: "MS203530",
    name: "Neetha",
    fromSJU: false,
    college: "Mount Carmel College autonomous",
    password: "8296936727",
    grpName: "Awakeners",
    css: cssValues["second"],
  },
  {
    rNum: "222ELCS42",
    name: "Yukta",
    college: "St. Joseph's University",
    fromSJU: true,
    password: "8008884493",
    grpName: "Eclairs",
    css: cssValues["first"],
  },
  {
    rNum: "MS203524",
    name: "Yukthi",
    college: "Mount Carmel College autonomous",
    fromSJU: false,
    password: "7019642831",
    grpName: "Awakeners",
    css: cssValues["third"],
  },
  {
    rNum: "223BCAB05",
    name: "Akarsh",
    college: "St. Joseph's University",
    fromSJU: true,
    password: "6282759838",
    grpName: "Sleepers",
    css: cssValues["second"],
  },
  {
    rNum: "223BCAB01",
    name: "Astle",
    college: "St. Joseph's University",
    fromSJU: true,
    password: "8590867797",
    grpName: "Eclairs",
    css: cssValues["second"],
  },
  {
    rNum: "2141152",
    name: "Lisa",
    college: "CHRIST (DEEMED TO BE UNIVERSITY), BANGALORE",
    fromSJU: false,
    password: "8434673061",
    grpName: "Awakeners",
    css: cssValues["third"],
  },
  {
    rNum: "223BCAB14",
    name: "Adwaith",
    college: "St. Joseph's University",
    fromSJU: true,
    password: "9895115798",
    grpName: "Sleepers",
    css: cssValues["third"],
  },
  {
    rNum: "223BCAB39",
    name: "Rino",
    college: "St. Joseph's University",
    fromSJU: false,
    password: "9061252777",
    grpName: "Eclairs",
    css: cssValues["third"],
  },
  {
    rNum: "MS203510",
    name: "Noor",
    college: "Mount Carmel College",
    fromSJU: false,
    password: "7019838258",
    grpName: "Eclairs",
    css: cssValues["third"],
  },
  {
    rNum: "MS203527",
    name: "Sneha",
    college: "Mount Carmel College",
    fromSJU: false,
    password: "8861020856",
    grpName: "Eclairs",
    css: cssValues["third"],
  },
  {
    rNum: "MS203519",
    name: "Umme",
    college: "Mount Carmel College",
    fromSJU: false,
    password: "8073280853",
    grpName: "Eclairs",
    css: cssValues["third"],
  },
  {
    rNum: "MS203511",
    name: "Pooja",
    college: "Mount Carmel College",
    fromSJU: false,
    password: "9008590507",
    grpName: "Eclairs",
    css: cssValues["third"],
  },
  {
    rNum: "MS203513",
    name: "Priyanka",
    college: "Mount Carmel College",
    fromSJU: false,
    password: "6364001572",
    grpName: "Eclairs",
    css: cssValues["third"],
  },
  {
    rNum: "MS203523",
    name: "Vasundhara",
    college: "Mount Carmel College",
    fromSJU: false,
    password: "7026447018",
    grpName: "Eclairs",
    css: cssValues["third"],
  },
  {
    rNum: "2140135",
    name: "Pranav",
    college: "Christ University",
    fromSJU: false,
    password: "8792901408",
    grpName: "Eclairs",
    css: cssValues["third"],
  },
  {
    rNum: "MS203533",
    name: "Sahar",
    college: "Mount Carmel College",
    fromSJU: false,
    password: "8123820558",
    grpName: "Eclairs",
    css: cssValues["third"],
  },
  {
    rNum: "MS203536",
    name: "Ritika",
    college: "Mount Carmel College",
    fromSJU: false,
    password: "7908842518",
    grpName: "Eclairs",
    css: cssValues["third"],
  },
  {
    rNum: "2140156",
    name: "Arpit",
    college: "Christ University",
    fromSJU: false,
    password: "9755798139",
    grpName: "Eclairs",
    css: cssValues["third"],
  },
  {
    rNum: "MS203506",
    name: "Merlin",
    college: "Mount Carmel College",
    fromSJU: false,
    password: "7639961131",
    grpName: "Eclairs",
    css: cssValues["third"],
  },
  {
    rNum: "MS203526",
    name: "Sikta",
    college: "Mount Carmel College",
    fromSJU: false,
    password: "7978956882",
    grpName: "Eclairs",
    css: cssValues["third"],
  },
  {
    rNum: "MS203520",
    name: "Yuktha",
    college: "Mount Carmel College",
    fromSJU: false,
    password: "9611077468",
    grpName: "Eclairs",
    css: cssValues["third"],
  },
  {
    rNum: "MS203537",
    name: "Nafeesa",
    college: "Mount Carmel College",
    fromSJU: false,
    password: "9611160239",
    grpName: "Eclairs",
    css: cssValues["third"],
  },
  {
    rNum: "MS214411",
    name: "Deepa",
    college: "Mount Carmel College",
    fromSJU: false,
    password: "8553486481",
    grpName: "Eclairs",
    css: cssValues["third"],
  },
  {
    rNum: "MS214408",
    name: "Sanjeetha",
    college: "Mount Carmel College",
    fromSJU: false,
    password: "7892475315",
    grpName: "Eclairs",
    css: cssValues["third"],
  },
  {
    rNum: "U18IW21S0106",
    name: "Revanth",
    college: "St Francis Degree College",
    fromSJU: false,
    password: "8310325579",
    grpName: "Eclairs",
    css: cssValues["third"],
  }
];

function getUserByRNum(rNum, password, grpName, socket) {
  let user = Users.find((val) => val.rNum === rNum);
  if (user.password != password || user.grpName != grpName) {
    socket.disconnect();
  }
  return user;
}

module.exports = { Users, getUserByRNum };
